name: Lint Check
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: run linter
    runs_on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Adjust based on your project's requirements

      - name: Install dependencies
        run: npm install  # Or yarn install, pnpm install based on your package manager

      - name: Run ESLint
        run: npm run lint 

